//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMicrobus.Core.Resources.Services.Staff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaffService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaffService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMicrobus.Core.Resources.Services.Staff.StaffService", typeof(StaffService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbus is already in queue..
        /// </summary>
        public static string Queue_Already_In_Queue {
            get {
                return ResourceManager.GetString("Queue_Already_In_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver not in queue..
        /// </summary>
        public static string Queue_Driver_Not_In_Queue {
            get {
                return ResourceManager.GetString("Queue_Driver_Not_In_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired QR code..
        /// </summary>
        public static string Queue_Invalid_QR {
            get {
                return ResourceManager.GetString("Queue_Invalid_QR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This microbus cannot start from this station..
        /// </summary>
        public static string Queue_Invalid_Start_Station {
            get {
                return ResourceManager.GetString("Queue_Invalid_Start_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbus not found..
        /// </summary>
        public static string Queue_Microbus_Not_Found {
            get {
                return ResourceManager.GetString("Queue_Microbus_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No routes found..
        /// </summary>
        public static string Queue_No_Routes {
            get {
                return ResourceManager.GetString("Queue_No_Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No queue found for this route at this station..
        /// </summary>
        public static string Queue_Not_Found {
            get {
                return ResourceManager.GetString("Queue_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan processed successfully..
        /// </summary>
        public static string Queue_Scan_Success {
            get {
                return ResourceManager.GetString("Queue_Scan_Success", resourceCulture);
            }
        }
    }
}
