//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMicrobus.Core.Resources.Services.Drivers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DriverService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriverService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMicrobus.Core.Resources.Services.Drivers.DriverService", typeof(DriverService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver information retrieved successfully..
        /// </summary>
        public static string Driver_Fetch_Success {
            get {
                return ResourceManager.GetString("Driver_Fetch_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No driver found for the given plate number..
        /// </summary>
        public static string Driver_Not_Found_By_Plate {
            get {
                return ResourceManager.GetString("Driver_Not_Found_By_Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver is currently available..
        /// </summary>
        public static string DriverAvailable {
            get {
                return ResourceManager.GetString("DriverAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver is currently in the queue..
        /// </summary>
        public static string DriverInQueue {
            get {
                return ResourceManager.GetString("DriverInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver is not in the queue..
        /// </summary>
        public static string DriverNotInQueue {
            get {
                return ResourceManager.GetString("DriverNotInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The driver is currently on a trip..
        /// </summary>
        public static string DriverOnTrip {
            get {
                return ResourceManager.GetString("DriverOnTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers count retrieved successfully..
        /// </summary>
        public static string DriversCountRetrieved {
            get {
                return ResourceManager.GetString("DriversCountRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver trip history retrieved successfully..
        /// </summary>
        public static string DriverTripHistoryRetrieved {
            get {
                return ResourceManager.GetString("DriverTripHistoryRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active trip found for the driver..
        /// </summary>
        public static string NoActiveTripFound {
            get {
                return ResourceManager.GetString("NoActiveTripFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No trips found for the specified period..
        /// </summary>
        public static string NoTripsFoundForPeriod {
            get {
                return ResourceManager.GetString("NoTripsFoundForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not your turn..
        /// </summary>
        public static string NotYourTurn {
            get {
                return ResourceManager.GetString("NotYourTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue retrieved successfully..
        /// </summary>
        public static string QueueRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("QueueRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip ended successfully..
        /// </summary>
        public static string TripEndedSuccessfully {
            get {
                return ResourceManager.GetString("TripEndedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip started successfully..
        /// </summary>
        public static string TripStartedSuccessfully {
            get {
                return ResourceManager.GetString("TripStartedSuccessfully", resourceCulture);
            }
        }
    }
}
