//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMicrobus.Core.Resources.Services.Route {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FavoriteRouteService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FavoriteRouteService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMicrobus.Core.Resources.Services.Route.FavoriteRouteService", typeof(FavoriteRouteService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite route not found..
        /// </summary>
        public static string FavoriteRouteNotFound {
            get {
                return ResourceManager.GetString("FavoriteRouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite routes retrieved successfully..
        /// </summary>
        public static string FavoriteRoutesRetrieved {
            get {
                return ResourceManager.GetString("FavoriteRoutesRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite status retrieved successfully..
        /// </summary>
        public static string IsFavoriteRetrieved {
            get {
                return ResourceManager.GetString("IsFavoriteRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite routes found..
        /// </summary>
        public static string NoFavoriteRoutesFound {
            get {
                return ResourceManager.GetString("NoFavoriteRoutesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger ID and Route ID are required..
        /// </summary>
        public static string PassengerIdAndRouteIdRequired {
            get {
                return ResourceManager.GetString("PassengerIdAndRouteIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger ID is required..
        /// </summary>
        public static string PassengerIdRequired {
            get {
                return ResourceManager.GetString("PassengerIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route added to favorites successfully..
        /// </summary>
        public static string RouteAddedToFavorites {
            get {
                return ResourceManager.GetString("RouteAddedToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This route is already in favorites..
        /// </summary>
        public static string RouteAlreadyInFavorites {
            get {
                return ResourceManager.GetString("RouteAlreadyInFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route not found..
        /// </summary>
        public static string RouteNotFound {
            get {
                return ResourceManager.GetString("RouteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route removed from favorites successfully..
        /// </summary>
        public static string RouteRemovedFromFavorites {
            get {
                return ResourceManager.GetString("RouteRemovedFromFavorites", resourceCulture);
            }
        }
    }
}
