//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMicrobus.Core.Resources.Services.Route {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoutesService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoutesService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMicrobus.Core.Resources.Services.Route.RoutesService", typeof(RoutesService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinations retrieved successfully..
        /// </summary>
        public static string DestinationsRetrieved {
            get {
                return ResourceManager.GetString("DestinationsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;From&apos; value is required..
        /// </summary>
        public static string FromValueRequired {
            get {
                return ResourceManager.GetString("FromValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbuses at station retrieved successfully..
        /// </summary>
        public static string MicrobusesAtStationRetrieved {
            get {
                return ResourceManager.GetString("MicrobusesAtStationRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microbuses on the way retrieved successfully..
        /// </summary>
        public static string MicrobusesOnTheWayRetrieved {
            get {
                return ResourceManager.GetString("MicrobusesOnTheWayRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No destinations found for the selected city..
        /// </summary>
        public static string NoDestinationsFound {
            get {
                return ResourceManager.GetString("NoDestinationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No microbuses available at the station for this route..
        /// </summary>
        public static string NoMicrobusesAtStation {
            get {
                return ResourceManager.GetString("NoMicrobusesAtStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No microbuses on the way for this route..
        /// </summary>
        public static string NoMicrobusesOnWay {
            get {
                return ResourceManager.GetString("NoMicrobusesOnWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No routes found..
        /// </summary>
        public static string NoRoutesFound {
            get {
                return ResourceManager.GetString("NoRoutesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route ID is required..
        /// </summary>
        public static string RouteIdRequired {
            get {
                return ResourceManager.GetString("RouteIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes retrieved successfully..
        /// </summary>
        public static string RoutesRetrievedSuccessfully {
            get {
                return ResourceManager.GetString("RoutesRetrievedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route summary retrieved successfully..
        /// </summary>
        public static string RouteSummaryRetrieved {
            get {
                return ResourceManager.GetString("RouteSummaryRetrieved", resourceCulture);
            }
        }
    }
}
