//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMicrobus.Core.Resources.Services.Stations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StationsService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StationsService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMicrobus.Core.Resources.Services.Stations.StationsService", typeof(StationsService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid station ID.
        /// </summary>
        public static string InvalidStationId {
            get {
                return ResourceManager.GetString("InvalidStationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest station found successfully.
        /// </summary>
        public static string NearestStationFound {
            get {
                return ResourceManager.GetString("NearestStationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stations found.
        /// </summary>
        public static string NoStationsFound {
            get {
                return ResourceManager.GetString("NoStationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route between stations retrieved successfully.
        /// </summary>
        public static string RouteBetweenStationsFound {
            get {
                return ResourceManager.GetString("RouteBetweenStationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station details with route retrieved successfully.
        /// </summary>
        public static string StationDetailsWithRouteFound {
            get {
                return ResourceManager.GetString("StationDetailsWithRouteFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station retrieved successfully.
        /// </summary>
        public static string StationFound {
            get {
                return ResourceManager.GetString("StationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station not found.
        /// </summary>
        public static string StationNotFound {
            get {
                return ResourceManager.GetString("StationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stations retrieved successfully.
        /// </summary>
        public static string StationsFound {
            get {
                return ResourceManager.GetString("StationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or both stations not found.
        /// </summary>
        public static string StationsNotFound {
            get {
                return ResourceManager.GetString("StationsNotFound", resourceCulture);
            }
        }
    }
}
