//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMicrobus.Core.Resources.Services.Report {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMicrobus.Core.Resources.Services.Report.ReportService", typeof(ReportService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plate number..
        /// </summary>
        public static string InvalidPlateNumber {
            get {
                return ResourceManager.GetString("InvalidPlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more reasons are invalid..
        /// </summary>
        public static string InvalidReasons {
            get {
                return ResourceManager.GetString("InvalidReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reported this driver recently..
        /// </summary>
        public static string Report_Already_Submitted {
            get {
                return ResourceManager.GetString("Report_Already_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid plate number..
        /// </summary>
        public static string Report_Invalid_Plate {
            get {
                return ResourceManager.GetString("Report_Invalid_Plate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more reasons are invalid..
        /// </summary>
        public static string Report_Invalid_Reasons {
            get {
                return ResourceManager.GetString("Report_Invalid_Reasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No report reasons found..
        /// </summary>
        public static string Report_Reasons_Not_Found {
            get {
                return ResourceManager.GetString("Report_Reasons_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons retrieved..
        /// </summary>
        public static string Report_Reasons_Retrieved {
            get {
                return ResourceManager.GetString("Report_Reasons_Retrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your report has been submitted successfully.
        ///The report will be reviewed and the appropriate action will be taken as soon as possible.
        ///Thank you for cooperating with Smart Microbus..
        /// </summary>
        public static string Report_Submitted_Success {
            get {
                return ResourceManager.GetString("Report_Submitted_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report deleted successfully..
        /// </summary>
        public static string ReportDeleted {
            get {
                return ResourceManager.GetString("ReportDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only delete reports that are in pending status..
        /// </summary>
        public static string ReportDeleteOnlyPending {
            get {
                return ResourceManager.GetString("ReportDeleteOnlyPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report not found..
        /// </summary>
        public static string ReportNotFound {
            get {
                return ResourceManager.GetString("ReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report retrieved successfully..
        /// </summary>
        public static string ReportRetrieved {
            get {
                return ResourceManager.GetString("ReportRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports retrieved successfully..
        /// </summary>
        public static string ReportsRetrieved {
            get {
                return ResourceManager.GetString("ReportsRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report updated successfully..
        /// </summary>
        public static string ReportUpdated {
            get {
                return ResourceManager.GetString("ReportUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only update reports that are in pending status..
        /// </summary>
        public static string ReportUpdateOnlyPending {
            get {
                return ResourceManager.GetString("ReportUpdateOnlyPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this report..
        /// </summary>
        public static string UnauthorizedAccessReport {
            get {
                return ResourceManager.GetString("UnauthorizedAccessReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to delete this report..
        /// </summary>
        public static string UnauthorizedDeleteReport {
            get {
                return ResourceManager.GetString("UnauthorizedDeleteReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to update this report..
        /// </summary>
        public static string UnauthorizedUpdateReport {
            get {
                return ResourceManager.GetString("UnauthorizedUpdateReport", resourceCulture);
            }
        }
    }
}
