//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMicrobus.Core.Resources.Services.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMicrobus.Core.Resources.Services.Account.AuthService", typeof(AuthService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account already confirmed..
        /// </summary>
        public static string ConfirmAccount_Already_Confirmed {
            get {
                return ResourceManager.GetString("ConfirmAccount_Already_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation data is required..
        /// </summary>
        public static string ConfirmAccount_Data_Required {
            get {
                return ResourceManager.GetString("ConfirmAccount_Data_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to confirm account..
        /// </summary>
        public static string ConfirmAccount_Failed {
            get {
                return ResourceManager.GetString("ConfirmAccount_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or expired OTP..
        /// </summary>
        public static string ConfirmAccount_Invalid_Or_Expired_Otp {
            get {
                return ResourceManager.GetString("ConfirmAccount_Invalid_Or_Expired_Otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///Your account has been successfully created in Smart Microbus.
        ///Your account confirmation code is: {0}
        ///Please do not share this code with anyone..
        /// </summary>
        public static string ConfirmAccount_Message {
            get {
                return ResourceManager.GetString("ConfirmAccount_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account confirmed successfully..
        /// </summary>
        public static string ConfirmAccount_Success {
            get {
                return ResourceManager.GetString("ConfirmAccount_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete account..
        /// </summary>
        public static string DeleteAccount_Failed {
            get {
                return ResourceManager.GetString("DeleteAccount_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully..
        /// </summary>
        public static string DeleteAccount_Success {
            get {
                return ResourceManager.GetString("DeleteAccount_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has no photo to delete..
        /// </summary>
        public static string DeleteUserPhoto_Not_Found {
            get {
                return ResourceManager.GetString("DeleteUserPhoto_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User photo deleted successfully..
        /// </summary>
        public static string DeleteUserPhoto_Success {
            get {
                return ResourceManager.GetString("DeleteUserPhoto_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        public static string ForgotPassword_Phone_Required {
            get {
                return ResourceManager.GetString("ForgotPassword_Phone_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an account with the provided phone number exists, an OTP has been sent..
        /// </summary>
        public static string ForgotPassword_Success_Generic {
            get {
                return ResourceManager.GetString("ForgotPassword_Success_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found with this phone number..
        /// </summary>
        public static string ForgotPassword_User_Not_Found {
            get {
                return ResourceManager.GetString("ForgotPassword_User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login data is required..
        /// </summary>
        public static string Login_Data_Required {
            get {
                return ResourceManager.GetString("Login_Data_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number or password..
        /// </summary>
        public static string Login_Invalid_Credentials {
            get {
                return ResourceManager.GetString("Login_Invalid_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not allowed to sign in..
        /// </summary>
        public static string Login_Not_Allowed {
            get {
                return ResourceManager.GetString("Login_Not_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number not confirmed. Please confirm your account before logging in..
        /// </summary>
        public static string Login_Phone_Not_Confirmed {
            get {
                return ResourceManager.GetString("Login_Phone_Not_Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account is locked. Please try again later or contact support..
        /// </summary>
        public static string Login_User_Locked {
            get {
                return ResourceManager.GetString("Login_User_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out successfully..
        /// </summary>
        public static string Logout_Success {
            get {
                return ResourceManager.GetString("Logout_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId is required..
        /// </summary>
        public static string Logout_UserId_Required {
            get {
                return ResourceManager.GetString("Logout_UserId_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait {0} seconds..
        /// </summary>
        public static string OTP_Cooldown {
            get {
                return ResourceManager.GetString("OTP_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send OTP. Please try again later..
        /// </summary>
        public static string OTP_Send_Failed {
            get {
                return ResourceManager.GetString("OTP_Send_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token is invalid..
        /// </summary>
        public static string RefreshToken_Access_Invalid {
            get {
                return ResourceManager.GetString("RefreshToken_Access_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required claim is missing in token..
        /// </summary>
        public static string RefreshToken_Claim_Missing {
            get {
                return ResourceManager.GetString("RefreshToken_Claim_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is invalid or expired..
        /// </summary>
        public static string RefreshToken_Invalid_Or_Expired {
            get {
                return ResourceManager.GetString("RefreshToken_Invalid_Or_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid refresh token..
        /// </summary>
        public static string RefreshToken_Invalid_Refresh {
            get {
                return ResourceManager.GetString("RefreshToken_Invalid_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token..
        /// </summary>
        public static string RefreshToken_Invalid_Token {
            get {
                return ResourceManager.GetString("RefreshToken_Invalid_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token refreshed successfully..
        /// </summary>
        public static string RefreshToken_Success {
            get {
                return ResourceManager.GetString("RefreshToken_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        public static string RefreshToken_User_Not_Exist {
            get {
                return ResourceManager.GetString("RefreshToken_User_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string RefreshToken_User_Not_Found {
            get {
                return ResourceManager.GetString("RefreshToken_User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register driver..
        /// </summary>
        public static string RegisterDriver_Failed {
            get {
                return ResourceManager.GetString("RegisterDriver_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver registered successfully..
        /// </summary>
        public static string RegisterDriver_Success {
            get {
                return ResourceManager.GetString("RegisterDriver_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register passenger..
        /// </summary>
        public static string RegisterPassenger_Failed {
            get {
                return ResourceManager.GetString("RegisterPassenger_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passenger registered successfully..
        /// </summary>
        public static string RegisterPassenger_Success {
            get {
                return ResourceManager.GetString("RegisterPassenger_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an account with the provided phone number exists, an OTP has been sent..
        /// </summary>
        public static string ResendConfirmation_Success_Generic {
            get {
                return ResourceManager.GetString("ResendConfirmation_Success_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset data is required..
        /// </summary>
        public static string ResetPassword_Data_Required {
            get {
                return ResourceManager.GetString("ResetPassword_Data_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset password..
        /// </summary>
        public static string ResetPassword_Failed {
            get {
                return ResourceManager.GetString("ResetPassword_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, {0} is your password recovery code..
        /// </summary>
        public static string ResetPassword_Message {
            get {
                return ResourceManager.GetString("ResetPassword_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully..
        /// </summary>
        public static string ResetPassword_Success {
            get {
                return ResourceManager.GetString("ResetPassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image type..
        /// </summary>
        public static string UploadPhoto_Invalid_Type {
            get {
                return ResourceManager.GetString("UploadPhoto_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file provided..
        /// </summary>
        public static string UploadPhoto_No_File {
            get {
                return ResourceManager.GetString("UploadPhoto_No_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size exceeds limit..
        /// </summary>
        public static string UploadPhoto_Size_Exceeded {
            get {
                return ResourceManager.GetString("UploadPhoto_Size_Exceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User photo uploaded successfully..
        /// </summary>
        public static string UploadPhoto_Success {
            get {
                return ResourceManager.GetString("UploadPhoto_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is required..
        /// </summary>
        public static string VerifyOtp_Data_Required {
            get {
                return ResourceManager.GetString("VerifyOtp_Data_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number or OTP..
        /// </summary>
        public static string VerifyOtp_Invalid_Data {
            get {
                return ResourceManager.GetString("VerifyOtp_Invalid_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No OTP found or it has expired..
        /// </summary>
        public static string VerifyOtp_Not_Found_Or_Expired {
            get {
                return ResourceManager.GetString("VerifyOtp_Not_Found_Or_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number not confirmed. Please confirm your account before resetting password..
        /// </summary>
        public static string VerifyOtp_Phone_Not_Confirmed_Reset {
            get {
                return ResourceManager.GetString("VerifyOtp_Phone_Not_Confirmed_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP verified successfully..
        /// </summary>
        public static string VerifyOtp_Success {
            get {
                return ResourceManager.GetString("VerifyOtp_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp service returned false..
        /// </summary>
        public static string WhatsApp_Send_Failed {
            get {
                return ResourceManager.GetString("WhatsApp_Send_Failed", resourceCulture);
            }
        }
    }
}
