//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMicrobus.Core.Resources.Services.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMicrobus.Core.Resources.Services.Admin.AdminService", typeof(AdminService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot lock an admin account..
        /// </summary>
        internal static string Cannot_Lock_Admin {
            get {
                return ResourceManager.GetString("Cannot_Lock_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create manager..
        /// </summary>
        internal static string CreateManager_Failed {
            get {
                return ResourceManager.GetString("CreateManager_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete manager..
        /// </summary>
        internal static string DeleteManager_Failed {
            get {
                return ResourceManager.GetString("DeleteManager_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager deleted successfully..
        /// </summary>
        internal static string DeleteManager_Success {
            get {
                return ResourceManager.GetString("DeleteManager_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to lock account..
        /// </summary>
        internal static string LockAccount_Failed {
            get {
                return ResourceManager.GetString("LockAccount_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked successfully..
        /// </summary>
        internal static string LockAccount_Success {
            get {
                return ResourceManager.GetString("LockAccount_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager added successfully..
        /// </summary>
        internal static string Manager_Added_Success {
            get {
                return ResourceManager.GetString("Manager_Added_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager not found..
        /// </summary>
        internal static string Manager_Not_Found {
            get {
                return ResourceManager.GetString("Manager_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager station updated successfully..
        /// </summary>
        internal static string Manager_Station_Updated_Success {
            get {
                return ResourceManager.GetString("Manager_Station_Updated_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station not found..
        /// </summary>
        internal static string Station_Not_Found {
            get {
                return ResourceManager.GetString("Station_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unlock account..
        /// </summary>
        internal static string UnlockAccount_Failed {
            get {
                return ResourceManager.GetString("UnlockAccount_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account unlocked successfully..
        /// </summary>
        internal static string UnlockAccount_Success {
            get {
                return ResourceManager.GetString("UnlockAccount_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string User_Not_Found {
            get {
                return ResourceManager.GetString("User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users retrieved successfully..
        /// </summary>
        internal static string Users_Retrieved_Success {
            get {
                return ResourceManager.GetString("Users_Retrieved_Success", resourceCulture);
            }
        }
    }
}
